### ISSUE TITLE
--round flag: what does it means?

### ISSUE THREAD

**Issue by thehulke** [Workshape/icon-font-generator#17] opened 2017-10-15 12:14 UTC
Hey, 
I have been trying your lib and it is awesome!
Just one thing.. when i generate the icons, each of them is slightly mutated.. i believe it has something to do with the `--round` flag.. please help me understand this better?

I have found a similar problem with no answer in [svgicons2svgfont issue #64](https://github.com/nfroidure/svgicons2svgfont/issues/64).

Thanks!

**Comment by ImanMh** [comment] 2018-04-18 08:59
I have the same issue. When I generate the font all my icons are like artwork and have corners. Is it related to --round? If yes, How can I disable it or reduce it to a very low number? I tried --round 0 but it didn't work.

**Comment by tancredi** [comment] 2018-04-18 09:08
@thehulke @ImanMh that may be due to the `--height` being very low by default (which means it's going to snap points to a small pixel grid if I get this correctly) - try with a high value (e.g. `--height=1000`) and let me know whether that works please.

**Comment by tancredi** [comment] 2018-04-18 09:26
Ok. @thehulke as suggested above try to see whether the issue is with the SVG size (even if units are not snapped in your SVGs I understand they will be snapped to the pixel grid according to the size in pixels of the largest SVG you feed the generator by default). Regarding the `--round` option, I don't know exactly how that works, it gets passed as it is to the https://github.com/nfroidure/svgicons2svgfont module, so maybe you'll get better answers on that repo.

Closing this for now.

**Closed by tancredi** 2018-04-18 09:26 UTC

**Comment by ImanMh** [comment] 2018-04-18 10:03
ThanX man you did great help. This tool is awesome.
