### ISSUE TITLE
Low quality output

### ISSUE THREAD

**Issue by ImanMh** [Workshape/icon-font-generator#30] opened 2018-04-18 09:17 UTC
Is there any way to control the quality of output? I give round and sharp SVGs but get a very bad output.

**Comment by tancredi** [comment] 2018-04-18 09:31
Yah I'm seeing what the problem is - the SVGs need a bit of cleanup - give me a minute - and maybe push access to that repo if you wanna make it easier :)

**Comment by tancredi** [comment] 2018-04-18 09:48
Ok @ImanMh so here's the problem:

The SVGs must be 1 color and possibly flattened out, not using masks or transparent layers - the font will be generated using the raw paths of the svg using a single color - attached are some of the example of how I amended your SVGs using Illustrator - also, the strokes must be expanded to paths, as stroke information and color information will be lost.

That, alongside with using `--height=200` made for a nice result, which is included in my fork of your repo - see the results here: https://github.com/tancredi/demonstrate-icon-font-issue

<img width="478" alt="screen shot 2018-04-18 at 10 29 32" src="https://user-images.githubusercontent.com/1300753/38924877-fe6e09ee-42f5-11e8-9b21-bc12d40e5d90.png">
<img width="555" alt="screen shot 2018-04-18 at 10 30 43" src="https://user-images.githubusercontent.com/1300753/38924878-fe86aa8a-42f5-11e8-9774-35d3d2e4f82a.png">
<img width="555" alt="screen shot 2018-04-18 at 10 30 49" src="https://user-images.githubusercontent.com/1300753/38924880-fe9fd474-42f5-11e8-8256-5ff0a8a94e15.png">

**Comment by tancredi** [comment] 2018-04-18 09:50
As you can see the instagram icon for example had a transparent square around itself - probably to maintain the artboard area and spacing in the original source you got it from. The last image displays the raw paths (If using Illustrator, toggle this view by using CMD+Y).

Hope this helps.

Closing the issue now :)

**Closed by tancredi** 2018-04-18 09:50 UTC

**Comment by ImanMh** [comment] 2018-04-18 10:03
ThanX man you did great help. This tool is awesome.

**Comment by tancredi** [comment] 2018-04-18 10:05
Cheers man I appreciate :)

**Comment by paulparton** [comment] 2018-08-30 23:58
super helpful answer. you should add something about this to the readme :)
